#!/usr/bin/env python
# -*- coding: utf-8 -*-
import cv2
import cv2.cv as cv
import numpy as np


def darkest_area(img):

    scalefactor = np.float32(2)
    img_small = cv2.resize(img, (0, 0), fx=(1/scalefactor), fy=(1/scalefactor))
    img_blur = cv2.blur(img_small, (25, 25))
    # img_gaussian = cv2.GaussianBlur(img, (401, 401), 0)

    #find position of darkest area
    index_y, index_x = np.where(img_blur == img_blur.min())

    #calculate center of multiple minimums
    center_coords_x = np.int(scalefactor*((np.amin(index_x) + np.amax(index_x)) / 2))
    center_coords_y = np.int(scalefactor*((np.amin(index_y) + np.amax(index_y)) / 2))


    return center_coords_x, center_coords_y
